### ISSUE TITLE
AOVPNDPC.msi is missing

### ISSUE THREAD

**Issue by Supaxor** [ld0614/DPC#1]
Hello,

Is the a way to download a pre-compiled DCP installer MSI please?

Have a nice day

**Comment by ld0614** [comment]
You can download a pre-built version from the releases link on the side of the main page

![image](https://github.com/user-attachments/assets/a4db34c3-422f-4197-b729-c6cd56f1aa15)

you can also use the link https://github.com/ld0614/DPC/releases/latest to be taken to the latest release

I've also updated the README file to reference the link as a few people have asked this question across different media

Thanks
Leo

**Comment by Supaxor** [comment]
Thanks a lot!
